### PR TITLE
l10n: attempt to localize the placeholder of textarea

### PR DESCRIPTION
**Pull request by alonbl**
this is working if cloudflare is disabled, for some reason setting the
placeholder attribute will not cause refresh for cloudflare.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

### CODE REVIEW

**Comment by alonbl** [comment]
we forgot to handle these two, not that important... but also not that trivial as it seems.

**Comment by inexorabletash** [comment]
This would be fine for now, but do you want to add in the Hebrew translations while you're there?

**Comment by inexorabletash** [comment]
Ah, yes, the loading of the localization code happens after CodeMirror converts the textarea...

**Comment by inexorabletash** [comment]
Okay, I pushed a fix that initializes CodeMirror after loc is complete.

(Initialization order is a bit of whack-a-mole, I need to rework it all.)

**Comment by alonbl** [comment]
great! working now.

**Pull request merged**
