### PR TITLE
Partial Hungarian translations

### PR DESCRIPTION
**Pull request by janoszen**
UI translations done, command translation missing

### CODE REVIEW

**Comment by inexorabletash** [comment]
Cool. How about error messages? (None of the other translations have those yet, though.)

**Comment by janoszen** [comment]
How do I translate those? I would be willing to do full translations if I get a little bit of guidance how to do that. :)

**Comment by inexorabletash** [comment]
I've added an example of all of the messages to the Esperanto translation.

**Comment by janoszen** [comment]
Cool, I'll look into it. Do you also want German translations? (Can do those too.)

**Comment by inexorabletash** [comment]
Sure!

**Comment by inexorabletash** [comment]
I updated the translation format a bit. Please take another look at the examples/docs

**Comment by inexorabletash** [comment]
I never merged this in and now the format has changed. :(

Any chance for an update?

**Comment by janoszen** [comment]
I'm super busy right now, but in a week I may find some time.

**Pull request closed without merging**
