### PR TITLE
Shorter Russian labels for links descriptions and buttons

### PR DESCRIPTION
**Pull request by alexeyev**
Hello,
here come a few minor modifications to fix [this](http://i.snag.gy/uHNdS.jpg) and [this](http://i.snag.gy/pArRx.jpg)

### CODE REVIEW

**Comment by inexorabletash** [comment]
Looks good. We can also tweak the layout if necessary.

**Comment by inexorabletash** [comment]
Oh, we need a translation for the "Stop" button seen when a long sequence is running, e.g.

`repeat 1000 [ fd 100 rt 37 wait 5 ]`

ID is `ip-button-stop`

**Comment by inexorabletash** [comment]
Google Translate suggested _Стоп_ so hopefully that's got the right connotation.

**Comment by alexeyev** [comment]
Yes, _Стоп_ is the perfect translation :)

**Pull request merged**
