### PR TITLE
spanish translation

### PR DESCRIPTION
**Pull request by JavGuerra**
Hi. Good job. I hope my Spanish translation can be helpful. Greetings.

### CODE REVIEW

**Comment by inexorabletash** [comment]
Awesome, thanks! I'll try to review/merge/publish soon

**Comment by inexorabletash** [comment]
Awesome. I think it just needs 3 more translations:

* "Commands you enter will appear here so you can find, modify, and re-run them."
* "Clear history: Are you sure?"
* "Clear library: Are you sure?"

If you provide those here, I'll add them to the file.

**Comment by JavGuerra** [comment]
Hi, 

I am sending you the translation that you indicate.

"Commands you enter will appear here so you can find, modify, and re-run them.": "Los comandos que introduzca aparecerán aquí para que pueda encontrarlos, modificarlos y volver a ejecutarlos.",
"Clear history: Are you sure?": "Limpiar el historial: ¿Está seguro?",
"Clear library: Are you sure?": "Limpiar la biblioteca: ¿Está seguro?",

Please could you also correct this? I think this new translation is better.

"tl-tests": "Pruebas",
"logo-ta-single-line.placeholder": "Introduzca su código aquí...",
"logo-ta-multi-line.placeholder": "Introduzca su código aquí...",

Thank you!

**Comment by inexorabletash** [comment]
Done, thanks!

**Pull request merged**
